"""Add configuration status tracking to UserPreferences

Revision ID: 001
Revises: 
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_configuration_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('configuration_started_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE user_preferences SET is_configuration_active = 0 WHERE is_configuration_active IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('configuration_started_at')
        batch_op.drop_column('is_configuration_active')
    # ### end Alembic commands ###